services:
  rpcn:
    image: k4rian/rpcn:latest
    container_name: rpcn
    volumes:
      - data:/home/rpcn
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - rpcn.env
    ports:
      - 33131:33131/tcp
      - 3657:3657/udp
    restart: unless-stopped

volumes:
  data: